dist: trusty
language: php
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json

before_script:
  - composer self-update
  - composer install --no-interaction
  - phpenv rehash

script:
  - "./vendor/bin/phplint ./ --exclude=vendor"
  - "./vendor/bin/phpunit"
